### ISSUE TITLE
Issue with value return

### ISSUE THREAD

**Issue by Skarabaen** [fr00sch/bosswerk_mi600_solar#1]
ret0 = getValueOfID(wait, "webdata_now_p")
        ret1 = getValueOfID(wait, "webdata_today_e")
        ret2 = getValueOfID(wait, "webdata_total_e")

the retrun of the above variables are only integer, so e.g. webdata_total_e value of 12.3 is only shown as 12.

**Comment by fr00sch** [comment]
Thanks for the hint, now it is giving back float for "webdata_today_e" and "webdata_total_e"

**Comment by Skarabaen** [comment]
thank you for the fix. 

For the MI600 offline issue I have put in a work around with an easy "ping the IP" script. If the MI600 is offline because of night, not enough power or network issues you can`t ping it and can send a mqtt message with status offline and power 0.0

**Comment by fr00sch** [comment]
No problem.

If you send me your script rows i try to adapt this function in the code.
