### ISSUE TITLE
Mqtt with login (easy fix)

### ISSUE THREAD

**Issue by Skarabaen** [fr00sch/bosswerk_mi600_solar#2]
Hello,

I dont know how to make a pull request so I write it down here for you :D 

Put in line 99 the code
client.username_pw_set(mqtt_username, mqtt_password)

and also adjust in your config section and the config file the two new variables "mqtt_username" and "mqtt_password". Now you can login to you mqtt broker.

**Comment by fr00sch** [comment]
Tank you for the tip.

I corrected the script and config-File, if you see any critical differences to your code, just write. ;-)
